@isTest
public class metadataServiceController_test {
    @isTest
    static void method1(){
        metadataServiceController metaservice = new  metadataServiceController();
        
        metadataServiceController.SaveResult  sR = new metadataServiceController.SaveResult();
        metadataServiceController.ExtendedErrorDetails   sv          =   new metadataServiceController.ExtendedErrorDetails();
        metadataServiceController.AllOrNoneHeader_element  allorNone =   new metadataServiceController.AllOrNoneHeader_element();
        metadataServiceController.SessionHeader_element  ses =   new metadataServiceController.SessionHeader_element();
        metadataServiceController.Error err =   new metadataServiceController.Error();
        metadataServiceController.DebuggingInfo_element  debug       =  new metadataServiceController.DebuggingInfo_element();
        metadataServiceController.CallOptions_element callops =   new metadataServiceController.CallOptions_element();
        metadataServiceController.Metadata mdd =   new metadataServiceController.Metadata();
        metadataServiceController.DebuggingHeader_element dh =   new metadataServiceController.DebuggingHeader_element();
        metadataServiceController.LogInfo lgi =   new metadataServiceController.LogInfo();
        metadataServiceController.createMetadataResponse_element crr =   new metadataServiceController.createMetadataResponse_element();
        metadataServiceController.deleteMetadata_element delemt =   new metadataServiceController.deleteMetadata_element();
        metadataServiceController.createMetadata_element  dfasd =   new metadataServiceController.createMetadata_element ();
        metadataServiceController.CustomField cs =   new metadataServiceController.CustomField();
        metadataServiceController.MetadataPort mp =   new metadataServiceController.MetadataPort();
        metadataServiceController.ProfileFieldLevelSecurity pfs =   new metadataServiceController.ProfileFieldLevelSecurity();
        metadataServiceController.Profile mpss =   new metadataServiceController.Profile();
        
        metadataServiceController.updateMetadata_element mpe =   new metadataServiceController.updateMetadata_element();
        metadataServiceController.updateMetadataResponse_element upme =   new metadataServiceController.updateMetadataResponse_element();
        
        
        system.assert(true);    
        // metaservice.SaveResult  sR=new metaservice.SaveResult();
        
    }
}